### PR TITLE
adding doc

### PR DESCRIPTION
**Pull request by 1ivliev**

### CODE REVIEW

**Comment by kamilsk** [comment]
why https://github.com/qase-tms/qase-phpunit/pull/3 ?

**Comment by 1ivliev** [comment]
> why #3 ?

there were a lot of edits, I decided to open a new pr

**Review by kamilsk — CHANGES_REQUESTED** [review]
please reduce commits and fix committer

**Review by kamilsk — CHANGES_REQUESTED** [review]
needs to check src/Reporter

**Pull request closed without merging**
